################################################################################
# Joshua C. Fjelstul, Ph.D.
# worldcup R package
# automatically generated by the codebookr R package
################################################################################

#' Confederations
#' 
#' This dataset records all FIFA confederations. There is one observation per
#' confederation. There are 5 variables and 6 observations.
#' 
#' @format A data frame with 5 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{confederation_id}{\code{text}. The unique ID number for the
#' confederation. Has the format \code{CF-#}, where the number is a counter
#' that is assigned with the confederations sorted in alphabetical order.}
#' \item{confederation_name}{\code{text}. The name of the confederation.}
#' \item{confederation_code}{\code{text}. The abbreviation for the
#' confederation.}
#' \item{confederation_wikipedia_link}{\code{text}. The Wikipedia link for the
#' confederation.}
#' }
"confederations"

################################################################################
# end R script
################################################################################

