################################################################################
# Joshua C. Fjelstul, Ph.D.
# worldcup R package
# automatically generated by the codebookr R package
################################################################################

#' Host countries
#' 
#' This dataset records all host countries. There is one observation per host
#' country per tournament. A tournament can have multiple host countries. It
#' indicates the performance of each host country (the furthest stage
#' reached). There are 7 variables and 31 observations.
#' 
#' @format A data frame with 7 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{tournament_id}{\code{text}. The unique ID number for the tournament.
#' References \code{tournament_id} in the \code{tournaments} dataset.}
#' \item{tournament_name}{\code{text}. The name of the tournament.}
#' \item{team_id}{\code{text}. The unique ID number for the team. References
#' \code{team_id} in the \code{teams} dataset.}
#' \item{team_name}{\code{text}. The name of the team.}
#' \item{team_code}{\code{text}. The 3-letter code for the team.}
#' \item{performance}{\code{text}. The furthest stage of the tournament
#' reached by the host country's team.}
#' }
"host_countries"

################################################################################
# end R script
################################################################################

