################################################################################
# Joshua C. Fjelstul, Ph.D.
# worldcup R package
# automatically generated by the codebookr R package
################################################################################

#' Player appearances
#' 
#' This dataset records all player appearances since 1970. There is one
#' observation per player per team per match per tournament. It includes
#' players who play in the match, including players who are in the starting
#' eleven and players who come in as substitutes. FIFA match reports do not
#' include information about substitutions before 1970. There are 21 variables
#' and 27432 observations.
#' 
#' @format A data frame with 21 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{tournament_id}{\code{text}. The unique ID number for the tournament.
#' References \code{tournament_id} in the \code{tournaments} dataset.}
#' \item{tournament_name}{\code{text}. The name of the tournament.}
#' \item{match_id}{\code{text}. The unique ID number for the match. References
#' \code{match_id} in the \code{matches} dataset.}
#' \item{match_name}{\code{text}. The name of the match.}
#' \item{match_date}{\code{date}. The date of the match in the format
#' \code{YYYY-MM-DD}.}
#' \item{stage_name}{\code{enum}. The stage of the tournament in which the
#' match occurred. The possible values are: \code{first round}, \code{second
#' round}, \code{group stage}, \code{round of sixteen}, \code{quarter-finals},
#' \code{semi-finals}, \code{third place match}, \code{final}. Note that not
#' all values are applicable to all tournaments.}
#' \item{group_name}{\code{text}. The name of the group.}
#' \item{team_id}{\code{text}. The unique ID number for the team of the
#' player. References \code{team_id} in the \code{teams} dataset.}
#' \item{team_name}{\code{text}. The name of the team of the player.}
#' \item{team_code}{\code{text}. The 3-letter code for the team of the
#' player.}
#' \item{home_team}{\code{boolean}. Whether the team was the home team. Coded
#' \code{1} if the team was the home team and \code{0} otherwise.}
#' \item{away_team}{\code{boolean}. Whether the team was the away team. Coded
#' \code{1} if the team was the away team and \code{0} otherwise.}
#' \item{player_id}{\code{text}. The unique ID number for the player.
#' References \code{player_id} in the \code{players} dataset.}
#' \item{family_name}{\code{text}. The family name of the player.}
#' \item{given_name}{\code{text}. The given name of the player.}
#' \item{shirt_number}{\code{integer}. The shirt number of the player.}
#' \item{position_name}{\code{text}. The name of the position of the player.}
#' \item{position_code}{\code{text}. A 2-letter or 3-letter code that
#' indicates the position of the player.}
#' \item{starter}{\code{boolean}. Whether the player started the match. Coded
#' \code{1} if the player started the match and \code{0} otherwise.}
#' \item{substitute}{\code{boolean}. Whether the player was a substitute.
#' Coded \code{1} if the player was a substitute and \code{0} otherwise.}
#' }
"player_appearances"

################################################################################
# end R script
################################################################################

