################################################################################
# Joshua C. Fjelstul, Ph.D.
# worldcup R package
# automatically generated by the codebookr R package
################################################################################

#' Referee appearances
#' 
#' This dataset records all referee appearances. There is one observation per
#' referee per match per tournament. There are 15 variables and 1248
#' observations.
#' 
#' @format A data frame with 15 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{tournament_id}{\code{text}. The unique ID number for the tournament.
#' References \code{tournament_id} in the \code{tournaments} dataset.}
#' \item{tournament_name}{\code{text}. The name of the tournament.}
#' \item{match_id}{\code{text}. The unique ID number for the match. References
#' \code{match_id} in the \code{matches} dataset.}
#' \item{match_name}{\code{text}. The name of the match.}
#' \item{match_date}{\code{date}. The date of the match in the format
#' \code{YYYY-MM-DD}.}
#' \item{stage_name}{\code{enum}. The stage of the tournament in which the
#' match occurred. The possible values are: \code{first round}, \code{second
#' round}, \code{group stage}, \code{round of sixteen}, \code{quarter-finals},
#' \code{semi-finals}, \code{third place match}, \code{final}. Note that not
#' all values are applicable to all tournaments.}
#' \item{group_name}{\code{text}. The name of the group.}
#' \item{referee_id}{\code{text}. The unique ID number for the referee.
#' References \code{referee_id} in the \code{referees} dataset.}
#' \item{family_name}{\code{text}. The family name of the referee.}
#' \item{given_name}{\code{text}. The given name of the referee.}
#' \item{country_name}{\code{text}. The name of the referee's home country.}
#' \item{confederation_id}{\code{text}. The unique ID number for the
#' confederation. References \code{confederation_id} in the
#' \code{confederations} dataset.}
#' \item{confederation_name}{\code{text}. The name of the confederation.}
#' \item{confederation_code}{\code{text}. The abbreviation for the
#' confederation.}
#' }
"referee_appearances"

################################################################################
# end R script
################################################################################

