################################################################################
# Joshua C. Fjelstul, Ph.D.
# worldcup R package
# automatically generated by the codebookr R package
################################################################################

#' Squads
#' 
#' This dataset records the composition of each squad. There is one
#' observation per player per team per tournament. It includes the position of
#' each player, the shirt number of each player (from 1954), the current club
#' of each player, and a link to the Wikipedia page for the club, if it has
#' one. There are 14 variables and 13843 observations.
#' 
#' @format A data frame with 12 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{tournament_id}{\code{text}. The unique ID number for the tournament.
#' References \code{tournament_id} in the \code{tournaments} dataset.}
#' \item{tournament_name}{\code{text}. The name of the tournament.}
#' \item{team_id}{\code{text}. The unique ID number for the team. References
#' \code{team_id} in the \code{teams} dataset.}
#' \item{team_name}{\code{text}. The name of the team of the player.}
#' \item{team_code}{\code{text}. The 3-letter code for the team.}
#' \item{player_id}{\code{text}. The unique ID number for the player.
#' References \code{player_id} in the \code{players} dataset.}
#' \item{family_name}{\code{text}. The family name of the player.}
#' \item{given_name}{\code{text}. The given name of the player.}
#' \item{shirt_number}{\code{integer}. The shirt number of the player.}
#' \item{position_name}{\code{enum}. The position of the player. The possible
#' values are: \code{goal keeper}, \code{defender}, \code{midfielder},
#' \code{forward}.}
#' \item{position_code}{\code{enum}. The code for the position of the player.
#' The possible values are: \code{GK}, \code{DF}, \code{MF}, \code{FW}.}
#' }
"squads"

################################################################################
# end R script
################################################################################

