################################################################################
# Joshua C. Fjelstul, Ph.D.
# worldcup R package
# automatically generated by the codebookr R package
################################################################################

#' Teams
#' 
#' This dataset records all teams who have participated in a World Cup match.
#' There is one observation per team. It includes the 3-letter ISO code for
#' each country and information about each country's national federation and
#' FIFA confederation. There are 11 variables and 84 observations.
#' 
#' @format A data frame with 11 variables:
#' \describe{
#' \item{key_id}{\code{integer}. The unique ID number for the observation.}
#' \item{team_id}{\code{text}. The unique ID number for the team. Has the
#' format \code{T-##}, where the number is a counter that is assigned with the
#' data sorted by the year of the team's first tournament and then by the
#' team's name.}
#' \item{team_name}{\code{text}. The name of the team.}
#' \item{team_code}{\code{text}. The 3-letter code for the team.}
#' \item{federation_name}{\code{text}. The name of the team's federation.}
#' \item{region_name}{\code{text}. The name of the region that the country is
#' located in.}
#' \item{confederation_id}{\code{text}. The unique ID number for the
#' confederation. References \code{confederation_id} in the
#' \code{confederations} dataset.}
#' \item{confederation_name}{\code{text}. The name of the confederation.}
#' \item{confederation_code}{\code{text}. The abbreviation for the
#' confederation.}
#' \item{team_wikipedia_link}{\code{text}. The Wikipedia link for the team.}
#' \item{federation_wikipedia_link}{\code{text}. The Wikipedia link of the
#' team's federation.}
#' }
"teams"

################################################################################
# end R script
################################################################################

